erDiagram

    club {
        BIGSERIAL id PK
        VARCHAR name UK
    }

    team {
        BIGSERIAL id PK
        VARCHAR name UK
        BIGINT club_id FK
        BIGINT league_id FK
    }

    player {
        BIGSERIAL id PK
        BIGINT team_id FK
        VARCHAR name
        INT shirt_number UK
    }

    league {
        BIGSERIAL id PK
        VARCHAR name
        BIGINT competition_id FK
    }

    competition {
        BIGSERIAL id PK
        VARCHAR name
    }

    match {
        BIGSERIAL id PK
        BIGINT home_team_id FK
        BIGINT away_team_id FK
        TIMESTAMPTZ scheduled_at
        BIGINT competition_id FK
        VARCHAR status "SCHEDULED|IN_PROGRESS|FINISHED|CANCELLED"
    }

    event {
        BIGSERIAL id PK
        BIGINT match_id FK,UK
        VARCHAR name
        NUMERIC price_normal
        NUMERIC price_supporter
        VARCHAR status "DRAFT|PUBLISHED|SALES_CLOSED|CANCELLED"
        VARCHAR description
    }

    ticket {
        BIGSERIAL id PK
        BIGINT event_id FK
        UUID code UK
        NUMERIC price
        VARCHAR status "PENDING|PAID|VALIDATED"
        VARCHAR payment_method "MBWAY|CARD|CASH"
        VARCHAR mbway_reference
        TIMESTAMPTZ created_at
        BIGINT validator_id FK
    }

  