server:
  port: 8083

spring:
  application:
    name: statistics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tessera_statistics
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
